version: 2.1

executors:
  maven-executor:
    docker:
      - image: maven:3.8.4-openjdk-17 # Use an image with Maven and OpenJDK 17

jobs:
  build:
    executor: maven-executor # Use the defined executor
    steps:
      - checkout # Check out the source code
      - run:
          name: Run Maven tests
          command: mvn test # Run unit tests with Maven

  upload-to-codecov:
    docker:
      - image: codecov/codecov:4.0.1 # Use the Codecov image
    steps:
      - checkout
      - run:
          name: Upload coverage report to Codecov
          command: codecov -f ./target/site/jacoco/jacoco.xml # Path to the coverage report
          environment:
            CODECOV_TOKEN: $CODECOV_TOKEN # Use your Codecov token as an environment variable

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master # Execute only on the master branch
      - upload-to-codecov: # This job runs after build job
          requires:
            - build
