version: 2.1

executors:
  maven-executor:
    docker:
      - image: maven:3.8.4-openjdk-17 # Use an image with Maven and OpenJDK 11

jobs:
  build:
    executor: maven-executor # Use the defined executor
    steps:
      - checkout # Check out the source code
      - run:
          name: Run Maven tests
          command: mvn test # Run unit tests with Maven

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master # Execute only on the master branch
